### ISSUE TITLE
Estructurar protocolo paso a paso del proceso de fabricación según tipo de retenedores.

### ISSUE THREAD

**Issue by ADLimportaciones** [ADLimportaciones/Labtek#1]
### Introducción
- [x] **Objetivo del protocolo:** Explicar el propósito del protocolo, detallando el tipo de retenedor que se va a fabricar.
- [x] **Alcance del protocolo:** Definir los límites del proceso y a quién va dirigido (técnicos de laboratorio, operarios, etc.).

### Insumos y máquinas requeridas
- [x] **Lista de materiales (Check-list)**
- [x] **Listado de equipos (Check-list)**

### Protocolo de fabricación
- [x] **Descripción detallada de tareas:** Detallar cada tarea a ejecutar para la fabricación del retenedor.
- [x] **Parámetros de fabricación:** Especificar los parámetros críticos según el proceso, como los parámetros de impresión 3D, temperaturas, y tiempos de termoformado.
- [ ] **Diagrama(s) de flujo:** Incluir diagramas que representen el flujo del proceso de fabricación.

### Seguridad y normativas
- [x] **Lista de riesgos:** Identificar los riesgos durante el proceso de fabricación.
- [ ] **Normativas y procedimientos de seguridad:** Especificar las normativas que deben seguirse para reducir los riesgos.

---

### Introducción
- [x] **Objetivo del protocolo:** Explicar el propósito del protocolo, detallando el tipo de férula que se va a fabricar.
- [x] **Alcance del protocolo:** Definir los límites del proceso y a quién va dirigido (técnicos de laboratorio, operarios, etc.).

### Insumos y máquinas requeridas
- [x] **Lista de materiales (Check-list)**
- [x] **Listado de equipos (Check-list)**

### Protocolo de fabricación
- [ ] **Descripción detallada de tareas:** Detallar cada tarea a ejecutar para la fabricación de la férula.
- [ ] **Parámetros de fabricación:** Especificar los parámetros críticos según el proceso, como los parámetros de impresión 3D

**Comment by NataliaJimenez29** [comment]
[Protocolo ortodoncia invisible.pdf](https://github.com/user-attachments/files/16848568/Protocolo.ortodoncia.invisible.pdf)

**Comment by NataliaJimenez29** [comment]
[protocolo ortodoncia.pdf](https://github.com/user-attachments/files/16875579/protocolo.ortodoncia.pdf)

**Comment by FabianGutierrez01** [comment]
Recopilatorio de tarea desarrollada

[Issue # 1 Estructurar protocolo paso a paso](https://docs.google.com/document/d/1xlKP4YSc5JBZ4wxo79Xn_YLRJFHodsOWYA4XdRceEAQ/edit#heading=h.hzm6q0d6vdvs)
