### ISSUE TITLE
Análisis de Costos de Producción

### ISSUE THREAD

**Issue by FabianGutierrez01** [ADLimportaciones/Labtek#18]
### Costos de insumos

- [x] Insumos consumidos durante la fabricación.
- [x] Insumos consumidos para una o más placas.
- [x] Depreciación de máquinas y equipos.

### Costos de personal

- [x] Costos de recursos humanos.
- [x] Costos por producto.
- [x] Número de productos necesarios para cubrir los gastos.
- [x] Costo de análisis del caso y realización de movimientos.

### Costos comerciales

- [x] Costos de personal.
- [x] Costos de material audiovisual.

### Valores de venta

- [x] Costo por unidad de tratamiento o producto.
- [x] Evaluación de costos en el mercado. (Determinar mínimos y máximos permisibles)

**Comment by ADLimportaciones** [comment]
### Análisis de costos

[Isuue # 18 Análisis de Costos de Producción](https://docs.google.com/spreadsheets/d/18M1NEMbPzbMoJ63gIu_8BSAj_IUYw_MOWWPFO9sntB8/edit?gid=0#gid=0)
