### ISSUE TITLE
Diseño de Plan de Estudios de 6 etapas

### ISSUE THREAD

**Issue by ADLimportaciones** [ADLimportaciones/Labtek#3]
### Estructurar un programa académico para una capacitación orientada a DentalCAD

El programa académico debe estar estructurado en seis etapas enfocando las capacitaciones en cumplir el siguiente objetivo:

Capacitar a 2 personas en el diseño de unidades dentales en un plazo de 6 semanas, mediante un plan de entrenamiento detallado que cubra la fabricación en zirconio y disilicato de litio, así como en rehabilitaciones cementadas y atornilladas. El plan incluirá aspectos teóricos, prácticos y material de apoyo para el seguimiento del progreso. Al finalizar el entrenamiento, se realizarán pruebas con casos fabricables en el centro de fresado Labtek.

---

### Capacitación # 1
- [x] Contenido de la capacitación.
- [x] Objetivos de la capacitación.
- [x] Lista de casos de uso a usar.

### Capacitación # 2
- [x] Contenido de la capacitación.
- [x] Objetivos de la capacitación.
- [x] Lista de casos de uso a usar.

### Capacitación # 3
- [x] Contenido de la capacitación.
- [x] Objetivos de la capacitación.
- [x] Lista de casos de uso a usar.

### Capacitación # 4
- [x] Contenido de la capacitación.
- [x] Objetivos de la capacitación.
- [x] Lista de casos de uso a usar.

### Capacitación # 5
- [x] Contenido de la capacitación.
- [x] Objetivos de la capacitación.
- [x] Lista de casos de uso a usar.

### Capacitación # 6
- [x] Contenido de la capacitación.
- [x] Objetivos de la capacitación.
- [x] Lista de casos de uso a usar.

---

### Estructurar la metodología a usar en las capacitaciones
- [x] Estructuración básica de las capacitaciones:
  - 3 horas teórico-prácticas.
  - 3 casos de estudio con su video de desarrollo.
  - 2 horas de tutoría.
  - 1 cartilla educativa.
  - 1 evaluación práctica.

**Comment by daniloCAD** [comment]
HOLA SOY DANILO ESTA ES MI PRIMERA VEZ USANDO EL GESTRO DE PROYECTOS

[ESTRUCTURACION DE CURSO SMILE PASTO.docx](https://github.com/user-attachments/files/16806447/ESTRUCTURACION.DE.CURSO.SMILE.PASTO.docx)
[METODOLOGIA.docx](https://github.com/user-attachments/files/16806446/METODOLOGIA.docx)

SIEMPRE TUYO DANILO

**Comment by ADLimportaciones** [comment]
### Estructura de plan de estudio en limpio (Formato pdf).

[Plan de Estudio - DentalCAD.pdf](https://github.com/user-attachments/files/16820599/Plan.de.Estudio.-.DentalCAD.pdf)
