### ISSUE TITLE
Estructurar plantillas a usar durante las capacitaciones

### ISSUE THREAD

**Issue by ADLimportaciones** [ADLimportaciones/Labtek#4]
## Estructurar las plantillas visuales a ser usadas para cada una de las capacitaciones

- [ ] **Presentaciones**: Crear una plantilla uniforme para diferentes tipos de presentaciones, que se utilizará en cada capacitación.
- [ ] **Documentos técnicos**: Desarrollar una plantilla general para la documentación escrita, incluyendo comunicados y otros documentos principalmente textuales.
- [ ] **Cartillas de estudio**: Diseñar una cartilla documental que sirva como material de apoyo en cada capacitación.
- [ ] **Casos de estudio**: Crear una plantilla para presentar los casos de estudio, detallando las características del caso, las exigencias del profesional, los parámetros de diseño, y las imágenes del caso.

**Comment by Dgomez-adl** [comment]
Presentación
https://www.canva.com/design/DAGPDpEc5ZE/xDrrcejGWhJ2f_CgxmVUkA/edit

**Comment by Dgomez-adl** [comment]
Documento
https://www.canva.com/design/DAGPK5DW41U/9uWOZJDsUMH_U-BubMeviw/edit

**Comment by Dgomez-adl** [comment]
Casos de estudio
https://www.canva.com/design/DAGPLPPVWJc/foJIw53p8wWXkopyoHqEfg/edit

**Comment by Dgomez-adl** [comment]
Logos e iconos, para el tercer documento me di cuenta que es prudente tenerlo, lo mas cercano a un manual de marca
https://www.canva.com/design/DAFxQNtVsqo/T15yihJgZ3qg-crzdhoP8A/edit

**Comment by Dgomez-adl** [comment]
Cartilla de estudio
https://www.canva.com/design/DAGPL22O6ts/xtLvLlthO7lOco5536P_6w/edit

**Comment by ADLimportaciones** [comment]
### Canva
- Link de carpeta donde se dejan todos los documentos editables generados.

[Capacitación DentalCAD (6 Etapas)](https://www.canva.com/folder/FAFPWFME6vQ)
