### ISSUE TITLE
Envio de equipos de computo

### ISSUE THREAD

**Issue by daniloCAD** [ADLimportaciones/Labtek#7]
### Revisión de equipos.

- [x] Verificación de componentes.
- [x] Reparación o mantenimiento según requiera.
- [x] Valoración de los equipos.

### Envio de equipos.

- [x] Embalaje de equipos.
- [x] Verificación de información de envio.
- [x] Envio de componentes.

**Comment by FabianGutierrez01** [comment]
### Comprobante o guía de envío.
<img src="https://github.com/user-attachments/assets/f162df86-04ac-4b8c-805a-3bee7f63eb0e" alt="Image" width="400"/>

### Valuación de los equipos remitidos.
[Dell Optiplex 9020 - Escritorio de factor de forma pequeño](https://www.amazon.com/-/es/Dell-Optiplex-9020-Escritorio-DisplayPort/dp/B08BJDFZRF/ref=sr_1_11?__mk_es_US=%C3%85M%C3%85%C5%BD%C3%95%C3%91&sr=8-11)
