### ISSUE TITLE
Diseño de material de apoyo (Capacitación #1)

### ISSUE THREAD

**Issue by daniloCAD** [ADLimportaciones/Labtek#8]
### Caso de estudio No 1.
- [x] **Escaneos requeridos:**
- [x] **Imágenes requeridas**
- [x] **Historia clínica:**
- [x] **Orden de trabajo:**
- [ ] **Estructura del viseo tutorial.**
- [ ] **Video tutorial del desarrollo del caso de estudio.**

### Caso de estudio No 2.
- [x] **Escaneos requeridos:**
- [x] **Imágenes requeridas**
- [x] **Historia clínica:**
- [x] **Orden de trabajo:**
- [ ] **Estructura del viseo tutorial.**
- [ ] **Video tutorial del desarrollo del caso de estudio.**

### Caso de estudio No 3.
- [x] **Escaneos requeridos:**
- [x] **Imágenes requeridas**
- [x] **Historia clínica:**
- [x] **Orden de trabajo:**
- [ ] **Estructura del viseo tutorial.**
- [ ] **Video tutorial del desarrollo del caso de estudio.**

### Cartilla de estudio.
- [x] ** Resumen general del contenido de la capacitación**
- [x] **Material de apoyo, 5 enlaces de material relacionado a la capacitación**

### Evaluación.
- [ ] **Preparación de caso de estudio**
- [ ] **Preparación de historia clínica y orden de proceso**

**Comment by ADLimportaciones** [comment]
### Casos de estudio
[01. Cementadas individuales](https://drive.google.com/drive/u/0/folders/1lRHpsQOoiRGR4s5u261-BG3Yicio1AOd)
Carpeta en Drive que contiene:
- 4 cosos de estudio 
- 2 materiales de apoyo

**Queda pendiente la estructuración de la evaluación**
