### ISSUE TITLE
Diseño de capacitación # 2

### ISSUE THREAD

**Issue by ADLimportaciones** [ADLimportaciones/Labtek#9]
### Presentación general (5 diapositivas)
Contenido mínimo:
- [x] **Conceptos teóricos:**
  - Incluir definiciones clave y fundamentos teóricos relacionados con el tema central de la capacitación.

- [x] **Objetivos**
  - Mostrar los objetivos de la capacitación y como se alcanzaran.
  
- [x] **Casos de ejemplo:**
  - Presentar ejemplos prácticos que ilustren cómo se aplican los conceptos teóricos en situaciones reales.
  
- [x] **Presentación de caso de estudio:**
  - Introducir un caso de estudio que será analizado en detalle, proporcionando el contexto y los objetivos del análisis.

### Contenido de la capacitación
Contenido mínimo:
- [ ] **Temas a tratar:**
  - Detallar los temas principales que se abordarán durante la capacitación.
  
- [x] **Horario aproximado de la capacitación:**
  - Proporcionar un cronograma estimado para cada sección o tema de la capacitación.
  
- [x] **Insumos o materiales requeridos:**
  - Listar los materiales, herramientas o recursos que los participantes necesitarán durante la capacitación.

### Caso de estudio
- [ ] **Escaneos requeridos:**

- [x] **Imágenes requeridas**
  
- [x] **Historia clínica:**
  - Proporcionar un resumen detallado de la historia clínica relevante del paciente o situación estudiada.
  
- [x] **Orden de trabajo:**
  - Detallar los requerimientos entregados por "el odontólogo" para el desarrollo del caso.

**Comment by FabianGutierrez01** [comment]
### Capacitación numero dos. 

[02.Cofias y cutback](https://drive.google.com/drive/u/0/folders/1L9DHZJRCSAy3jTcr5zEPXlTc_Tt9bpZ7)
Carpeta de drive que contiene:

Presentación.
Cartillas capacitación numero 1.
Casos de estudio.
